### ISSUE TITLE
[Feature Request] Support for OGG Vorbis

### ISSUE THREAD

**Issue by Hund** [MaxFour/Music-Player#10]
Hi! It would be nice if it would support OGG Vorbis. It's a pretty player and it would be nice to not have to use VLC for my music. :)

**Comment by MaxFour** [comment]
OGG Vorbis (.ogg) is already supported.

**Comment by Hund** [comment]
Oh, I see. I guess there's something wrong with LineageOS then.

**Comment by Hund** [comment]
I found the issue. I needed to install an application that forced a rescan of my storage and after that it worked.

**Comment by concatime** [comment]
@Hund which application did you use? Trying to solve #12, I get `<file>.ogg is not listed in the media store`.

**Comment by Hund** [comment]
@concatime I'm using Music Player, but it works with both the default music player in LineageOS and the VLC Media Player client as well.

**Comment by concatime** [comment]
My bad, I wasn’t clear. Which "application that forced a rescan" did you use?

**Comment by Hund** [comment]
Ah! I used this. :)

https://f-droid.org/en/packages/com.gmail.jerickson314.sdscanner/
