### ISSUE TITLE
Music-Player[1.0.1] App not  installed

### ISSUE THREAD

**Issue by Icramss** [MaxFour/Music-Player#2]
# Expected behavior

I should be able to install the app after downloading the apk file.

# Actual behavior

The app shows **app not installed** after downloading the apk and trying to install it.

# How to reproduce

- go to https://github.com/MaxFour/Music-Player/releases
- Tap on ` Music.Player.v.1.0.1.apk `
- wait a moment downloading
- When finished, Click Open and install the app
- App not installed
- Write a bug there

### Device: ONE PLUS 2 OxygenOS Version 3.6.1
Operating System:Android 6.0.1
App Version :1.0.1
Browser : chrome

# Recording of the bug

https://youtu.be/j_ZrlvbGOeA

**Comment by MaxFour** [comment]
Hi!
I will fix it very soon.

Have a nice day ☺️

**Comment by Icramss** [comment]
Thanks .
