### ISSUE TITLE
Application failed to get install

### ISSUE THREAD

**Issue by adisalat2** [MaxFour/Music-Player#3]
Project Information
-Repository
https://github.com/MaxFour/Music-Player
-Downloadable from
https://github.com/MaxFour/Music-Player/releases

Expected Behaviour
Application should be install successfully after it have been downloaded

Actual Behaviour
Application was unable to be install after downloading 

How to reproduce
Download the application from github release
Install the application
Hence the bug

-Browser: Music player v 1.01
-Operating System:Android 7.0

Recording of the bug

https://youtu.be/LN-Jq1FE-fk

**Comment by MaxFour** [comment]
Hello!
Thank you for bugreport.
I will fix it very soon.

Have a nice day ;)
