### ISSUE TITLE
Missing playlists tab nor menu entry

### ISSUE THREAD

**Issue by Anth0rx** [MaxFour/Music-Player#33]
It is possible to create playlists but where can I find them? There is neither a "Playlists" tab, nor is there an entry in the menu.

**Comment by MaxFour** [comment]
Hello!
You can create playlist in a "Playlists" tab, tap a three dots button (beside search icon) and Create playlist

**Comment by Anth0rx** [comment]
But how do I access the playlist?

**Comment by MaxFour** [comment]
Go to settings->Library Categories->Check box "Playlists"

**Comment by Anth0rx** [comment]
Well, that's good to know. Thank you very much :+1:
