### ISSUE TITLE
[OT] How do you differentiate yourself from both Phonograph and Vinyl Music Player?

### ISSUE THREAD

**Issue by Tom4tot** [MaxFour/Music-Player#39]
Hi, your app is interesting, however, I was wondering, what are the differences between your app and the two others I mentioned? From what I've seen in the features list and the screenshot, it looks exactly the same...

I'm not trying to deny your work or anything, I'd just like to know what can i get from trying your app?

Thank you in advance. :)

**Comment by MaxFour** [comment]
Hello @Tom4tot !
Firstly, in my player all plurals in strings are fixed.
Secondly, in `Phonograph` and `Vinyl Music Player` an equalizer option in the Settings, and I moved equalizer to drawer.
Thirdly, in my player there are no dependences of Google Service and other analytical services.
In the end, in my player all the icons and images look more modern than in other players.

Good luck

**Comment by Tom4tot** [comment]
> Hello @Tom4tot !
> Firstly, in my player all plurals in strings are fixed.
> Secondly, in `Phonograph` and `Vinyl Music Player` an equalizer option in the Settings, and I moved equalizer to drawer.
> Thirdly, in my player there are no dependences of Google Service and other analytical services.
> In the end, in my player all the icons and images look more modern than in other players.
> 
> Good luck

All right, thank you for your answer. I understand your project better now. I think it would be good if you would add these pieces of information on the readme.md page, as the advantages of your player will interest a lot of people (especially the third one).

I was wondering as well, do you know where the images downloaded are stored? For covers. I never managed to find the folder.

**Comment by MaxFour** [comment]
> I was wondering as well, do you know where the images downloaded are stored?

I didn’t delve into it, but they can be in `data/` folder in root of device

**Comment by moriel5** [comment]
Hi, I was wondering the same thing when trying out the app.
Thanks for the explanation (though personally I prefer the old-school filled icons), this looks great.

Do you think that you could somehow (I realize that I am asking for something extremely hard when considering that the app is already very efficient) get the app's size down to ~2.5MB?
This is something I had asked the Phonograph developers, and they only managed to shave ~100KB from the their app.

**Comment by MaxFour** [comment]
Hello! In order for the application to weigh less, need to optimize the code (it is very difficult) or remove unnecessary activity (in this app, all activity are important and interrelated).

But you can try [Music Player GO](https://f-droid.org/en/packages/com.iven.musicplayergo/)

**Comment by moriel5** [comment]
Thanks, I had tried Music Player GO, and while I had certainly liked it, some features (like Album covers) are not planned to implemented.
Currently I use Oddysey, which is my favorite so far, though there are a few (minor) options that I would prefer to be otherwise, and it is not planned to be otherwise.

Currently, your app brings things the closest to my liking, not includong file size.
