### ISSUE TITLE
Playlist duplicates

### ISSUE THREAD

**Issue by bushrang3r** [MaxFour/Music-Player#41]
### Actual behaviour
- Create playlists
- Close app
- On next start, each playlist is duplicated

### Environment data
Android version: 8.1.0

Device model: Galaxy Note 4 (SM-N910F)

Stock or customized system: Resurrection Remix (LineageOS)

Music-Player app version: 1.2.1

**Comment by MaxFour** [comment]
Hi! I don't have this issue. Maybe this is the problem of Custom ROM or the problem of Android 8.1

**Comment by gkeegan** [comment]
I have this issue as well. On Android 8.0.0 with Emui 8.

**Comment by bushrang3r** [comment]
Hi. Yes, I think you must be right.
I have upgraded to Pie 9.0 (same custom rom) and this problem seems to have disappeared and I'm using the same app version too.

**Comment by MaxFour** [comment]
Hi! I'm glad that the problem was solved. Thank you for using my app :)
