### ISSUE TITLE
track number change when change music on card view

### ISSUE THREAD

**Issue by madeindjs** [MaxFour/Music-Player#42]
![screenshot_20181128-182945](https://user-images.githubusercontent.com/11815139/49170128-c21b7700-f33b-11e8-8939-8aa9efb7e300.jpg)
### Actual behaviour
- track number change when change music on card view

### Expected behaviour
- track number should no change and keep same
 
### Steps to reproduce
1. Go to album and start listen
2. Go down to tracklist  
3. Click on one track

### Environment data
Android version: 8.0

Device model: Hawei P8 9 lite 2017

Stock or customized system:

Music-Player app version: 1.2.1

**Comment by MaxFour** [comment]
Hi! It's a normal behavior.
The song that is currently being played is marked 0.
Songs up to 0 are marked -1, -2,...,-n
Songs after 0 are marked +1,+2,...,+n

It is a simple arithmetic :wink:

**Comment by madeindjs** [comment]
OK it's a misunderstanding. I think that it was a track number. Thank you for your answer
