### ISSUE TITLE
Certain mp3 files won't play after update to 1.2.1

### ISSUE THREAD

**Issue by lynxlynx** [MaxFour/Music-Player#43]
### Actual behaviour
After update to 1.2.1, certain well formed and long tested audio files (mp3) stopped playing at all: they get skipped in playlist, and when I tap them explicitly, player simply won't play them.
VLC and 1.2.0 do play them fine.

### Expected behaviour
Play all valid files as was it before.
Had to downgrade to 1.2.0 in F-Droid.
 
### Steps to reproduce
I have no idea what's going on. :-(

### Environment data
Android version:
Cyanogenmod 13.0

Device model: 
LG-D410

Stock or customized system:
Custom.

Music-Player app version:
1.2.1 F-Droid

**Comment by MaxFour** [comment]
Hi! 
Try to 'Reset all data' of Music Player

**Comment by lynxlynx** [comment]
Complete reinstallation of player with uninstall first helped! I was too naive trusting F-Droid to update the app. Still, that's maybe not too comfort when you have e.g. a lengthy Blacklist. Thanks!
