### ISSUE TITLE
Support albumart.jpg and albumart.png cover art files

### ISSUE THREAD

**Issue by scottywz** [MaxFour/Music-Player#50]
### Actual behaviour
I have albums in folders with `albumart.jpg` files but no embedded cover art.  The generic cover art is shown instead of `albumart.jpg` when "Ignore Media Store covers" is enabled.

### Expected behaviour
I expect to see the cover art from the `albumart.jpg` file.  (This file name is consistent with [the AOSP MediaScanner's `getCompressedAlbumArt()` method](https://android.googlesource.com/platform/packages/providers/MediaProvider/+/pie-release/src/com/android/providers/media/MediaProvider.java#4292) (which is case-insensitive despite the comment there).  Note that `albumart.png` will also be picked up by that algorithm, and in fact I do have covers with that name.

### Steps to reproduce
1. Enable "Ignore Media Store covers".
2. Make a folder containing a music file with no embedded cover art and no cover art files.
3. Add an `albumart.jpg` or `albumart.png` file to that folder.
4. Trigger a rescan if necessary.
5. Observe that the generic album art is shown in place of the file from step 3.

### Notes

MediaScanner does use a more complex algorithm where names containing "albumart" and names starting with "albumart" and ending in "large" are also accepted, but this issue is meant for the more common cases of "albumart.jpg" and "albumart.png", which can easily be added to the `FALLBACKS` constant in [AudioFileCoverFetcher.java](https://github.com/MaxFour/Music-Player/blob/master/app/src/main/java/com/maxfour/music/glide/audiocover/AudioFileCoverFetcher.java).

### Environment data
Android version: 8.1

Device model: Moto E 2015 LTE

Stock or customized system: unofficial Oreo image

Music-Player app version: 1.2.1

**Comment by MaxFour** [comment]
Hi! I merged your PR.

**Comment by Kowalski7** [comment]
For me it works if I name them as cover.jpg
