### ISSUE TITLE
Privacy Policy.

### ISSUE THREAD

**Issue by HarryHeights** [MaxFour/Music-Player#8]
Hi I'm Harry.

Would you like a privacy policy for your project?  I've done some for some projects here on github you can check them out if you like and if you are interested, I could do same for you.

However I'll need some information to make the document flawless and suit your project perfectly.
Thanks.

**Comment by MaxFour** [comment]
Hello Harry!

Thanks for the offer! it would be nice to make privacy policy.

About information, 
this is a simple player with useful features based on Photograph, without Google Services and without data collection (analytics).

Thank you!

**Comment by HarryHeights** [comment]
Alright. I'll get to work right away. Thanks for your reply.

**Comment by HarryHeights** [comment]
Hello, I've created a pull request for the policy document I proposed. Please check it out and make necessary changes. Thanks for allowing me be a part of your project.

**Comment by MaxFour** [comment]
Much thanks! I pulled your request.

**Comment by HarryHeights** [comment]
You are very welcome. You can send me a mail nwosaharry@gmail.com incase you need any documentation work done.

**Comment by MaxFour** [comment]
OK. Thank again!

**Comment by HarryHeights** [comment]
Hello there. It's me again. I saw an opened issue of someone requesting to draft a compilation of FAQs. It's been 18 days already, If you don't mind I could just go ahead and create the FAQs document instead. What do you think?

**Comment by MaxFour** [comment]
Hello!

I think that now I don't need FAQ because the project is simple and understandable.
Thank you for suggestion!

**Comment by HarryHeights** [comment]
Okay I understand. I guess this mean there are not much plan for advanced dev of the app

**Comment by MaxFour** [comment]
Yes, you are right.

**Comment by HarryHeights** [comment]
Oh okay. I was expecting greater things to come in the future though. Anyway I'm not a developer but I know these things aren't really easy.
