### ISSUE TITLE
Can't open album or artist on Android 11

### ISSUE THREAD

**Issue by bungabunga** [MaxFour/Music-Player#89]
### Actual behaviour
Since upgrading to Android 11 I can no longer click on artists and albums. Nothing happens if i try. Clicking on songs still plays songs.
Doing the same on similar music players (Shuffle+, Phonograph) works.

### Expected behaviour
Clicking on artist should open a list of songs by that artist, clicking on album should open a list of songs on that album.
 
### Steps to reproduce
1. find an album or artist
2. click on it
3. nothing happens

### Environment data
Android version: 11

Device model: Pixel 3

Stock or customized system: GrapheneOS (a privacy/security hardened android based on AOSP)

Music-Player latest F-droid build (1.3.3) Also tried the github build.

**Comment by MaxFour** [comment]
Hi! Can you check version 1.3.4?

**Comment by bungabunga** [comment]
Hi! It works! Thank you so much!
👍🙏✨🎉🎈
